version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: property-zone-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB_URI=mongodb+srv://shrivasv671:RBaVPMX9nlzSPtQc@cluster0.ra6sqlr.mongodb.net/BSRDB?retryWrites=true&w=majority
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - property-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: property-zone-frontend:dev
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      # Important: use service name `backend` instead of localhost
      - VITE_SERVER=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - property-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - property-net

networks:
  property-net:
    driver: bridge
